//: Playground - noun: a place where people can play

//import Cocoa
// import Swiftz
//: fmap: `<^> <A, B>(A -> B, a: F<A>) -> F<B>`     Functor
import func Swiftz.<^>
//: apply: `<*> <A, B>(F<A -> B>, F<A>) -> F<B>`    Applicative
import func Swiftz.<*>
//: bind: `>>- <A, B>(F<A>, A -> F<B>) -> F<B>`
import func Swiftz.>>-

let str : String? = .Some("Sam")

let greeting = { "Hello \($0)!" } <^> str 
print(greeting)

//greeting("hi")
//
/// result now contains either an array of file paths or the error generated by `NSFileManager`.
//let result : Result<[String]> = from { ep in
//    let documentsDir = NSSearchPathForDirectoriesInDomains(
//            .DocumentDirectory, .UserDomainMask, true)[0] as! String
//    let contentsOf = NSFileManager.defaultManager().contentsOfDirectoryAtPath
//    return contentsOf(documentsDir, error: ep) as? [String] ?? []
//}
//result
//
//let x = Maybe(2)
//let a = Maybe<Int>.none()
//let y = a.fmap({ $0 * 2 })
//y.isJust()
//y.isNone()



//let t = Maybe { x, y -> Int in x * y } <*> Maybe((2, 8)) //<*> Maybe(8)




